# Generated by Django 5.1.2 on 2024-11-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
