# Generated by Django 5.1.2 on 2024-11-07 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_of_payment",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="дата оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "наличные"), ("CARD", "безналичные")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
