# Generated by Django 5.1.2 on 2024-11-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_date_of_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
