# Generated by Django 5.1.2 on 2024-11-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
