# Generated by Django 5.1.2 on 2024-11-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ast_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
