# Generated by Django 5.1.2 on 2024-11-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_ast_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ast_login",
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
